// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/download (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/download_repository.go -mock_names=Repository=DownloadRepository -package mock github.com/pikoci/registry/pkreg/download Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// DownloadRepository is a mock of Repository interface.
type DownloadRepository struct {
	ctrl     *gomock.Controller
	recorder *DownloadRepositoryMockRecorder
	isgomock struct{}
}

// DownloadRepositoryMockRecorder is the mock recorder for DownloadRepository.
type DownloadRepositoryMockRecorder struct {
	mock *DownloadRepository
}

// NewDownloadRepository creates a new mock instance.
func NewDownloadRepository(ctrl *gomock.Controller) *DownloadRepository {
	mock := &DownloadRepository{ctrl: ctrl}
	mock.recorder = &DownloadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DownloadRepository) EXPECT() *DownloadRepositoryMockRecorder {
	return m.recorder
}

// RecordDownload mocks base method.
func (m *DownloadRepository) RecordDownload(ctx context.Context, versionID, tokenHash, ipHash string, date time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDownload", ctx, versionID, tokenHash, ipHash, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordDownload indicates an expected call of RecordDownload.
func (mr *DownloadRepositoryMockRecorder) RecordDownload(ctx, versionID, tokenHash, ipHash, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDownload", reflect.TypeOf((*DownloadRepository)(nil).RecordDownload), ctx, versionID, tokenHash, ipHash, date)
}
