// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/namespace (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/namespace_repository.go -mock_names=Repository=NamespaceRepository -package mock github.com/pikoci/registry/pkreg/namespace Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	namespace "github.com/pikoci/registry/pkreg/namespace"
	gomock "go.uber.org/mock/gomock"
)

// NamespaceRepository is a mock of Repository interface.
type NamespaceRepository struct {
	ctrl     *gomock.Controller
	recorder *NamespaceRepositoryMockRecorder
	isgomock struct{}
}

// NamespaceRepositoryMockRecorder is the mock recorder for NamespaceRepository.
type NamespaceRepositoryMockRecorder struct {
	mock *NamespaceRepository
}

// NewNamespaceRepository creates a new mock instance.
func NewNamespaceRepository(ctrl *gomock.Controller) *NamespaceRepository {
	mock := &NamespaceRepository{ctrl: ctrl}
	mock.recorder = &NamespaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *NamespaceRepository) EXPECT() *NamespaceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *NamespaceRepository) Create(ctx context.Context, ns namespace.Namespace) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ns)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *NamespaceRepositoryMockRecorder) Create(ctx, ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*NamespaceRepository)(nil).Create), ctx, ns)
}

// Delete mocks base method.
func (m *NamespaceRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *NamespaceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*NamespaceRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *NamespaceRepository) FindByID(ctx context.Context, id string) (*namespace.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*namespace.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *NamespaceRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*NamespaceRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *NamespaceRepository) FindByName(ctx context.Context, name string) (*namespace.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*namespace.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *NamespaceRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*NamespaceRepository)(nil).FindByName), ctx, name)
}

// FindByOwnerID mocks base method.
func (m *NamespaceRepository) FindByOwnerID(ctx context.Context, ownerID string) ([]*namespace.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].([]*namespace.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *NamespaceRepositoryMockRecorder) FindByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*NamespaceRepository)(nil).FindByOwnerID), ctx, ownerID)
}

// Update mocks base method.
func (m *NamespaceRepository) Update(ctx context.Context, ns namespace.Namespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ns)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *NamespaceRepositoryMockRecorder) Update(ctx, ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*NamespaceRepository)(nil).Update), ctx, ns)
}
