// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/orgmember (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/orgmember_repository.go -mock_names=Repository=OrgMemberRepository -package mock github.com/pikoci/registry/pkreg/orgmember Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	orgmember "github.com/pikoci/registry/pkreg/orgmember"
	gomock "go.uber.org/mock/gomock"
)

// OrgMemberRepository is a mock of Repository interface.
type OrgMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *OrgMemberRepositoryMockRecorder
	isgomock struct{}
}

// OrgMemberRepositoryMockRecorder is the mock recorder for OrgMemberRepository.
type OrgMemberRepositoryMockRecorder struct {
	mock *OrgMemberRepository
}

// NewOrgMemberRepository creates a new mock instance.
func NewOrgMemberRepository(ctrl *gomock.Controller) *OrgMemberRepository {
	mock := &OrgMemberRepository{ctrl: ctrl}
	mock.recorder = &OrgMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OrgMemberRepository) EXPECT() *OrgMemberRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *OrgMemberRepository) Create(ctx context.Context, om orgmember.OrgMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, om)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *OrgMemberRepositoryMockRecorder) Create(ctx, om any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*OrgMemberRepository)(nil).Create), ctx, om)
}

// Delete mocks base method.
func (m *OrgMemberRepository) Delete(ctx context.Context, orgID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *OrgMemberRepositoryMockRecorder) Delete(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*OrgMemberRepository)(nil).Delete), ctx, orgID, userID)
}

// FilterByOrg mocks base method.
func (m *OrgMemberRepository) FilterByOrg(ctx context.Context, orgID string) ([]*orgmember.OrgMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByOrg", ctx, orgID)
	ret0, _ := ret[0].([]*orgmember.OrgMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByOrg indicates an expected call of FilterByOrg.
func (mr *OrgMemberRepositoryMockRecorder) FilterByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByOrg", reflect.TypeOf((*OrgMemberRepository)(nil).FilterByOrg), ctx, orgID)
}

// FindByOrgAndUser mocks base method.
func (m *OrgMemberRepository) FindByOrgAndUser(ctx context.Context, orgID, userID string) (*orgmember.OrgMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrgAndUser", ctx, orgID, userID)
	ret0, _ := ret[0].(*orgmember.OrgMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrgAndUser indicates an expected call of FindByOrgAndUser.
func (mr *OrgMemberRepositoryMockRecorder) FindByOrgAndUser(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrgAndUser", reflect.TypeOf((*OrgMemberRepository)(nil).FindByOrgAndUser), ctx, orgID, userID)
}
