// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/regtype (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/regtype_repository.go -mock_names=Repository=RegTypeRepository -package mock github.com/pikoci/registry/pkreg/regtype Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	regtype "github.com/pikoci/registry/pkreg/regtype"
	gomock "go.uber.org/mock/gomock"
)

// RegTypeRepository is a mock of Repository interface.
type RegTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *RegTypeRepositoryMockRecorder
	isgomock struct{}
}

// RegTypeRepositoryMockRecorder is the mock recorder for RegTypeRepository.
type RegTypeRepositoryMockRecorder struct {
	mock *RegTypeRepository
}

// NewRegTypeRepository creates a new mock instance.
func NewRegTypeRepository(ctrl *gomock.Controller) *RegTypeRepository {
	mock := &RegTypeRepository{ctrl: ctrl}
	mock.recorder = &RegTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RegTypeRepository) EXPECT() *RegTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *RegTypeRepository) Create(ctx context.Context, rt regtype.RegType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *RegTypeRepositoryMockRecorder) Create(ctx, rt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*RegTypeRepository)(nil).Create), ctx, rt)
}

// Delete mocks base method.
func (m *RegTypeRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *RegTypeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*RegTypeRepository)(nil).Delete), ctx, id)
}

// FilterByNamespace mocks base method.
func (m *RegTypeRepository) FilterByNamespace(ctx context.Context, nsID string) ([]*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByNamespace", ctx, nsID)
	ret0, _ := ret[0].([]*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByNamespace indicates an expected call of FilterByNamespace.
func (mr *RegTypeRepositoryMockRecorder) FilterByNamespace(ctx, nsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByNamespace", reflect.TypeOf((*RegTypeRepository)(nil).FilterByNamespace), ctx, nsID)
}

// FindByID mocks base method.
func (m *RegTypeRepository) FindByID(ctx context.Context, id string) (*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *RegTypeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*RegTypeRepository)(nil).FindByID), ctx, id)
}

// FindByNamespaceAndName mocks base method.
func (m *RegTypeRepository) FindByNamespaceAndName(ctx context.Context, nsID, name, kind string) (*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNamespaceAndName", ctx, nsID, name, kind)
	ret0, _ := ret[0].(*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNamespaceAndName indicates an expected call of FindByNamespaceAndName.
func (mr *RegTypeRepositoryMockRecorder) FindByNamespaceAndName(ctx, nsID, name, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNamespaceAndName", reflect.TypeOf((*RegTypeRepository)(nil).FindByNamespaceAndName), ctx, nsID, name, kind)
}

// Search mocks base method.
func (m *RegTypeRepository) Search(ctx context.Context, params regtype.SearchParams) (*regtype.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].(*regtype.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *RegTypeRepositoryMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*RegTypeRepository)(nil).Search), ctx, params)
}

// Update mocks base method.
func (m *RegTypeRepository) Update(ctx context.Context, rt regtype.RegType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *RegTypeRepositoryMockRecorder) Update(ctx, rt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*RegTypeRepository)(nil).Update), ctx, rt)
}
