// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/service.go -mock_names=Service=Service -package mock github.com/pikoci/registry/pkreg Service
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	namespace "github.com/pikoci/registry/pkreg/namespace"
	regtype "github.com/pikoci/registry/pkreg/regtype"
	tag "github.com/pikoci/registry/pkreg/tag"
	token "github.com/pikoci/registry/pkreg/token"
	user "github.com/pikoci/registry/pkreg/user"
	version "github.com/pikoci/registry/pkreg/version"
	gomock "go.uber.org/mock/gomock"
)

// Service is a mock of Service interface.
type Service struct {
	ctrl     *gomock.Controller
	recorder *ServiceMockRecorder
	isgomock struct{}
}

// ServiceMockRecorder is the mock recorder for Service.
type ServiceMockRecorder struct {
	mock *Service
}

// NewService creates a new mock instance.
func NewService(ctrl *gomock.Controller) *Service {
	mock := &Service{ctrl: ctrl}
	mock.recorder = &ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Service) EXPECT() *ServiceMockRecorder {
	return m.recorder
}

// ClaimOrgNamespace mocks base method.
func (m *Service) ClaimOrgNamespace(ctx context.Context, userID, githubOrgLogin string) (*namespace.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOrgNamespace", ctx, userID, githubOrgLogin)
	ret0, _ := ret[0].(*namespace.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOrgNamespace indicates an expected call of ClaimOrgNamespace.
func (mr *ServiceMockRecorder) ClaimOrgNamespace(ctx, userID, githubOrgLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOrgNamespace", reflect.TypeOf((*Service)(nil).ClaimOrgNamespace), ctx, userID, githubOrgLogin)
}

// CreateToken mocks base method.
func (m *Service) CreateToken(ctx context.Context, userID, nsName, name string) (*token.Token, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, userID, nsName, name)
	ret0, _ := ret[0].(*token.Token)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *ServiceMockRecorder) CreateToken(ctx, userID, nsName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*Service)(nil).CreateToken), ctx, userID, nsName, name)
}

// DeleteType mocks base method.
func (m *Service) DeleteType(ctx context.Context, userID, ns, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteType", ctx, userID, ns, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteType indicates an expected call of DeleteType.
func (mr *ServiceMockRecorder) DeleteType(ctx, userID, ns, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteType", reflect.TypeOf((*Service)(nil).DeleteType), ctx, userID, ns, name)
}

// DeleteVersion mocks base method.
func (m *Service) DeleteVersion(ctx context.Context, userID, ns, name, ver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVersion", ctx, userID, ns, name, ver)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVersion indicates an expected call of DeleteVersion.
func (mr *ServiceMockRecorder) DeleteVersion(ctx, userID, ns, name, ver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVersion", reflect.TypeOf((*Service)(nil).DeleteVersion), ctx, userID, ns, name, ver)
}

// DeprecateVersion mocks base method.
func (m *Service) DeprecateVersion(ctx context.Context, userID, ns, name, ver, message, successor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeprecateVersion", ctx, userID, ns, name, ver, message, successor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeprecateVersion indicates an expected call of DeprecateVersion.
func (mr *ServiceMockRecorder) DeprecateVersion(ctx, userID, ns, name, ver, message, successor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeprecateVersion", reflect.TypeOf((*Service)(nil).DeprecateVersion), ctx, userID, ns, name, ver, message, successor)
}

// FetchVersionContent mocks base method.
func (m *Service) FetchVersionContent(ctx context.Context, ns, name, ver, tokenHash, ip string) (*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchVersionContent", ctx, ns, name, ver, tokenHash, ip)
	ret0, _ := ret[0].(*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchVersionContent indicates an expected call of FetchVersionContent.
func (mr *ServiceMockRecorder) FetchVersionContent(ctx, ns, name, ver, tokenHash, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchVersionContent", reflect.TypeOf((*Service)(nil).FetchVersionContent), ctx, ns, name, ver, tokenHash, ip)
}

// GetCurrentUser mocks base method.
func (m *Service) GetCurrentUser(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *ServiceMockRecorder) GetCurrentUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*Service)(nil).GetCurrentUser), ctx, userID)
}

// GetGitHubClientID mocks base method.
func (m *Service) GetGitHubClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitHubClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGitHubClientID indicates an expected call of GetGitHubClientID.
func (mr *ServiceMockRecorder) GetGitHubClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitHubClientID", reflect.TypeOf((*Service)(nil).GetGitHubClientID))
}

// GetNamespace mocks base method.
func (m *Service) GetNamespace(ctx context.Context, name string) (*namespace.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", ctx, name)
	ret0, _ := ret[0].(*namespace.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *ServiceMockRecorder) GetNamespace(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*Service)(nil).GetNamespace), ctx, name)
}

// GetType mocks base method.
func (m *Service) GetType(ctx context.Context, ns, name string) (*regtype.RegType, []*version.Version, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType", ctx, ns, name)
	ret0, _ := ret[0].(*regtype.RegType)
	ret1, _ := ret[1].([]*version.Version)
	ret2, _ := ret[2].([]string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetType indicates an expected call of GetType.
func (mr *ServiceMockRecorder) GetType(ctx, ns, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*Service)(nil).GetType), ctx, ns, name)
}

// GetVersion mocks base method.
func (m *Service) GetVersion(ctx context.Context, ns, name, ver string) (*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, ns, name, ver)
	ret0, _ := ret[0].(*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *ServiceMockRecorder) GetVersion(ctx, ns, name, ver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*Service)(nil).GetVersion), ctx, ns, name, ver)
}

// GitHubLogin mocks base method.
func (m *Service) GitHubLogin(ctx context.Context, code string) (*user.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitHubLogin", ctx, code)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GitHubLogin indicates an expected call of GitHubLogin.
func (mr *ServiceMockRecorder) GitHubLogin(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitHubLogin", reflect.TypeOf((*Service)(nil).GitHubLogin), ctx, code)
}

// InviteOrgMember mocks base method.
func (m *Service) InviteOrgMember(ctx context.Context, userID, org, invitee, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteOrgMember", ctx, userID, org, invitee, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteOrgMember indicates an expected call of InviteOrgMember.
func (mr *ServiceMockRecorder) InviteOrgMember(ctx, userID, org, invitee, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteOrgMember", reflect.TypeOf((*Service)(nil).InviteOrgMember), ctx, userID, org, invitee, role)
}

// ListMyTypes mocks base method.
func (m *Service) ListMyTypes(ctx context.Context, userID string) ([]*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyTypes", ctx, userID)
	ret0, _ := ret[0].([]*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyTypes indicates an expected call of ListMyTypes.
func (mr *ServiceMockRecorder) ListMyTypes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyTypes", reflect.TypeOf((*Service)(nil).ListMyTypes), ctx, userID)
}

// ListNamespaceTypes mocks base method.
func (m *Service) ListNamespaceTypes(ctx context.Context, ns string) ([]*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespaceTypes", ctx, ns)
	ret0, _ := ret[0].([]*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNamespaceTypes indicates an expected call of ListNamespaceTypes.
func (mr *ServiceMockRecorder) ListNamespaceTypes(ctx, ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespaceTypes", reflect.TypeOf((*Service)(nil).ListNamespaceTypes), ctx, ns)
}

// ListTags mocks base method.
func (m *Service) ListTags(ctx context.Context) ([]*tag.TagCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]*tag.TagCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *ServiceMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*Service)(nil).ListTags), ctx)
}

// ListTokens mocks base method.
func (m *Service) ListTokens(ctx context.Context, nsName string) ([]*token.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", ctx, nsName)
	ret0, _ := ret[0].([]*token.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTokens indicates an expected call of ListTokens.
func (mr *ServiceMockRecorder) ListTokens(ctx, nsName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*Service)(nil).ListTokens), ctx, nsName)
}

// ListTypesByTag mocks base method.
func (m *Service) ListTypesByTag(ctx context.Context, tagName string) ([]*regtype.RegType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTypesByTag", ctx, tagName)
	ret0, _ := ret[0].([]*regtype.RegType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTypesByTag indicates an expected call of ListTypesByTag.
func (mr *ServiceMockRecorder) ListTypesByTag(ctx, tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTypesByTag", reflect.TypeOf((*Service)(nil).ListTypesByTag), ctx, tagName)
}

// PublishVersion mocks base method.
func (m *Service) PublishVersion(ctx context.Context, userID, ns, name, ver string, manifestBytes, readmeBytes []byte) (*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVersion", ctx, userID, ns, name, ver, manifestBytes, readmeBytes)
	ret0, _ := ret[0].(*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishVersion indicates an expected call of PublishVersion.
func (mr *ServiceMockRecorder) PublishVersion(ctx, userID, ns, name, ver, manifestBytes, readmeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVersion", reflect.TypeOf((*Service)(nil).PublishVersion), ctx, userID, ns, name, ver, manifestBytes, readmeBytes)
}

// RevokeToken mocks base method.
func (m *Service) RevokeToken(ctx context.Context, userID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, userID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *ServiceMockRecorder) RevokeToken(ctx, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*Service)(nil).RevokeToken), ctx, userID, tokenID)
}

// SearchTypes mocks base method.
func (m *Service) SearchTypes(ctx context.Context, query, kind, tagFilter, ns string, page, perPage int) (*regtype.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTypes", ctx, query, kind, tagFilter, ns, page, perPage)
	ret0, _ := ret[0].(*regtype.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTypes indicates an expected call of SearchTypes.
func (mr *ServiceMockRecorder) SearchTypes(ctx, query, kind, tagFilter, ns, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTypes", reflect.TypeOf((*Service)(nil).SearchTypes), ctx, query, kind, tagFilter, ns, page, perPage)
}

// UpdateTypeTags mocks base method.
func (m *Service) UpdateTypeTags(ctx context.Context, userID, ns, name string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTypeTags", ctx, userID, ns, name, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTypeTags indicates an expected call of UpdateTypeTags.
func (mr *ServiceMockRecorder) UpdateTypeTags(ctx, userID, ns, name, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTypeTags", reflect.TypeOf((*Service)(nil).UpdateTypeTags), ctx, userID, ns, name, tags)
}

// YankVersion mocks base method.
func (m *Service) YankVersion(ctx context.Context, userID, ns, name, ver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "YankVersion", ctx, userID, ns, name, ver)
	ret0, _ := ret[0].(error)
	return ret0
}

// YankVersion indicates an expected call of YankVersion.
func (mr *ServiceMockRecorder) YankVersion(ctx, userID, ns, name, ver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "YankVersion", reflect.TypeOf((*Service)(nil).YankVersion), ctx, userID, ns, name, ver)
}
