// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/tag (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/tag_repository.go -mock_names=Repository=TagRepository -package mock github.com/pikoci/registry/pkreg/tag Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	tag "github.com/pikoci/registry/pkreg/tag"
	gomock "go.uber.org/mock/gomock"
)

// TagRepository is a mock of Repository interface.
type TagRepository struct {
	ctrl     *gomock.Controller
	recorder *TagRepositoryMockRecorder
	isgomock struct{}
}

// TagRepositoryMockRecorder is the mock recorder for TagRepository.
type TagRepositoryMockRecorder struct {
	mock *TagRepository
}

// NewTagRepository creates a new mock instance.
func NewTagRepository(ctrl *gomock.Controller) *TagRepository {
	mock := &TagRepository{ctrl: ctrl}
	mock.recorder = &TagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TagRepository) EXPECT() *TagRepositoryMockRecorder {
	return m.recorder
}

// FilterByRegType mocks base method.
func (m *TagRepository) FilterByRegType(ctx context.Context, typeID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByRegType", ctx, typeID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByRegType indicates an expected call of FilterByRegType.
func (mr *TagRepositoryMockRecorder) FilterByRegType(ctx, typeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByRegType", reflect.TypeOf((*TagRepository)(nil).FilterByRegType), ctx, typeID)
}

// FilterRegTypesByTag mocks base method.
func (m *TagRepository) FilterRegTypesByTag(ctx context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRegTypesByTag", ctx, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterRegTypesByTag indicates an expected call of FilterRegTypesByTag.
func (mr *TagRepositoryMockRecorder) FilterRegTypesByTag(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRegTypesByTag", reflect.TypeOf((*TagRepository)(nil).FilterRegTypesByTag), ctx, arg1)
}

// ListWithCounts mocks base method.
func (m *TagRepository) ListWithCounts(ctx context.Context) ([]*tag.TagCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithCounts", ctx)
	ret0, _ := ret[0].([]*tag.TagCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithCounts indicates an expected call of ListWithCounts.
func (mr *TagRepositoryMockRecorder) ListWithCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithCounts", reflect.TypeOf((*TagRepository)(nil).ListWithCounts), ctx)
}

// ListWithCountsFiltered mocks base method.
func (m *TagRepository) ListWithCountsFiltered(ctx context.Context, kind, query string, limit int) ([]*tag.TagCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithCountsFiltered", ctx, kind, query, limit)
	ret0, _ := ret[0].([]*tag.TagCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithCountsFiltered indicates an expected call of ListWithCountsFiltered.
func (mr *TagRepositoryMockRecorder) ListWithCountsFiltered(ctx, kind, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithCountsFiltered", reflect.TypeOf((*TagRepository)(nil).ListWithCountsFiltered), ctx, kind, query, limit)
}

// SetForRegType mocks base method.
func (m *TagRepository) SetForRegType(ctx context.Context, typeID string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForRegType", ctx, typeID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForRegType indicates an expected call of SetForRegType.
func (mr *TagRepositoryMockRecorder) SetForRegType(ctx, typeID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForRegType", reflect.TypeOf((*TagRepository)(nil).SetForRegType), ctx, typeID, tags)
}
