// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/token (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/token_repository.go -mock_names=Repository=TokenRepository -package mock github.com/pikoci/registry/pkreg/token Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	token "github.com/pikoci/registry/pkreg/token"
	gomock "go.uber.org/mock/gomock"
)

// TokenRepository is a mock of Repository interface.
type TokenRepository struct {
	ctrl     *gomock.Controller
	recorder *TokenRepositoryMockRecorder
	isgomock struct{}
}

// TokenRepositoryMockRecorder is the mock recorder for TokenRepository.
type TokenRepositoryMockRecorder struct {
	mock *TokenRepository
}

// NewTokenRepository creates a new mock instance.
func NewTokenRepository(ctrl *gomock.Controller) *TokenRepository {
	mock := &TokenRepository{ctrl: ctrl}
	mock.recorder = &TokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TokenRepository) EXPECT() *TokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *TokenRepository) Create(ctx context.Context, t token.Token) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *TokenRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*TokenRepository)(nil).Create), ctx, t)
}

// Delete mocks base method.
func (m *TokenRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *TokenRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*TokenRepository)(nil).Delete), ctx, id)
}

// FilterByNamespace mocks base method.
func (m *TokenRepository) FilterByNamespace(ctx context.Context, nsID string) ([]*token.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByNamespace", ctx, nsID)
	ret0, _ := ret[0].([]*token.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByNamespace indicates an expected call of FilterByNamespace.
func (mr *TokenRepositoryMockRecorder) FilterByNamespace(ctx, nsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByNamespace", reflect.TypeOf((*TokenRepository)(nil).FilterByNamespace), ctx, nsID)
}

// FindByHash mocks base method.
func (m *TokenRepository) FindByHash(ctx context.Context, hash string) (*token.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(*token.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *TokenRepositoryMockRecorder) FindByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*TokenRepository)(nil).FindByHash), ctx, hash)
}
