// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/registry/pkreg/version (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/version_repository.go -mock_names=Repository=VersionRepository -package mock github.com/pikoci/registry/pkreg/version Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	version "github.com/pikoci/registry/pkreg/version"
	gomock "go.uber.org/mock/gomock"
)

// VersionRepository is a mock of Repository interface.
type VersionRepository struct {
	ctrl     *gomock.Controller
	recorder *VersionRepositoryMockRecorder
	isgomock struct{}
}

// VersionRepositoryMockRecorder is the mock recorder for VersionRepository.
type VersionRepositoryMockRecorder struct {
	mock *VersionRepository
}

// NewVersionRepository creates a new mock instance.
func NewVersionRepository(ctrl *gomock.Controller) *VersionRepository {
	mock := &VersionRepository{ctrl: ctrl}
	mock.recorder = &VersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VersionRepository) EXPECT() *VersionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *VersionRepository) Create(ctx context.Context, v version.Version) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *VersionRepositoryMockRecorder) Create(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*VersionRepository)(nil).Create), ctx, v)
}

// Delete mocks base method.
func (m *VersionRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *VersionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*VersionRepository)(nil).Delete), ctx, id)
}

// FilterByRegType mocks base method.
func (m *VersionRepository) FilterByRegType(ctx context.Context, typeID string) ([]*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByRegType", ctx, typeID)
	ret0, _ := ret[0].([]*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByRegType indicates an expected call of FilterByRegType.
func (mr *VersionRepositoryMockRecorder) FilterByRegType(ctx, typeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByRegType", reflect.TypeOf((*VersionRepository)(nil).FilterByRegType), ctx, typeID)
}

// FindByID mocks base method.
func (m *VersionRepository) FindByID(ctx context.Context, id string) (*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *VersionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*VersionRepository)(nil).FindByID), ctx, id)
}

// FindByRegTypeAndNumber mocks base method.
func (m *VersionRepository) FindByRegTypeAndNumber(ctx context.Context, typeID, arg2 string) (*version.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRegTypeAndNumber", ctx, typeID, arg2)
	ret0, _ := ret[0].(*version.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRegTypeAndNumber indicates an expected call of FindByRegTypeAndNumber.
func (mr *VersionRepositoryMockRecorder) FindByRegTypeAndNumber(ctx, typeID, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRegTypeAndNumber", reflect.TypeOf((*VersionRepository)(nil).FindByRegTypeAndNumber), ctx, typeID, arg2)
}

// IncrementDownloads mocks base method.
func (m *VersionRepository) IncrementDownloads(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDownloads", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDownloads indicates an expected call of IncrementDownloads.
func (mr *VersionRepositoryMockRecorder) IncrementDownloads(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDownloads", reflect.TypeOf((*VersionRepository)(nil).IncrementDownloads), ctx, id)
}

// Update mocks base method.
func (m *VersionRepository) Update(ctx context.Context, v version.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *VersionRepositoryMockRecorder) Update(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*VersionRepository)(nil).Update), ctx, v)
}
